# Generated by Django 5.2.4 on 2025-07-22 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dof3a_base", "0002_remove_comment_likes_comment_liked_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="friends",
            field=models.ManyToManyField(blank=True, to="dof3a_base.student"),
        ),
        migrations.CreateModel(
            name="FriendRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_accepted", models.BooleanField(default=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "from_student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_requests",
                        to="dof3a_base.student",
                    ),
                ),
                (
                    "to_student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_requests",
                        to="dof3a_base.student",
                    ),
                ),
            ],
            options={
                "unique_together": {("from_student", "to_student")},
            },
        ),
    ]
